name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Access
      run: chmod +x gradlew
    - name: Validate Gradle wrapper
      run: ./gradlew wrapper --gradle-version 6.8.3

    - name: Run static code analysis
      run: ./gradlew checkstyleMain

    - name: Build with Gradle
      run: ./gradlew build

    - name: Publish JAR Artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-app
        path: build/libs/*.jar
